<?php

use Illuminate\Database\Seeder;

use Faker\Factory;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

    	DB::table('products')->insert([
            // Token Listrik
    		[
	            'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 20.000',
                'category'      => 'PLN',
                'price'         => 20000,
                'province'      => null,
                'region'        => null,
	            'code'          => '1101',
                'status'        => 1,
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'PLN',
                'price'         => 50000,
                'province'      => null,
                'region'        => null,
                'code'          => '1101',
                'status'        => 1,
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'PLN',
                'price'         => 100000,
                'province'      => null,
                'region'        => null,
                'code'          => '1101',
                'status'        => 1,
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 200.000',
                'category'      => 'PLN',
                'price'         => 200000,
                'province'      => null,
                'region'        => null,
                'code'          => '1101',
                'status'        => 1,
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 500.000',
                'category'      => 'PLN',
                'price'         => 500000,
                'province'      => null,
                'region'        => null,
                'code'          => '1101',
                'status'        => 1,
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 1.000.000',
                'category'      => 'PLN',
                'price'         => 1000000,
                'province'      => null,
                'region'        => null,
                'code'          => '1101',
                'status'        => 1,
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
            ],

            // Tagihan Listrik
            [
                'name'          => 'Tagihan Listrik',
                'variant_name'  => null,
                'category'      => 'PLN',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1102',
                'status'        => 1,
                'dji_product_id' => '100301',
                'type'          => 'Postpaid',
            ],

            // PDAM
            [
                'name'          => 'PDAM Kab Banyumas',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB BANYUMAS',
                'code'          => '1201',
                'status'        => 1,
                'dji_product_id' => '400011',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Kebumen',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB KEBUMEN',
                'code'          => '1202',
                'status'        => 1,
                'dji_product_id' => '400021',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Magelang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KOTA MAGELANG',
                'code'          => '1203',
                'status'        => 1,
                'dji_product_id' => '400041',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Cilacap',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB CILACAP',
                'code'          => '1204',
                'status'        => 1,
                'dji_product_id' => '400051',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Semarang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KOTA SEMARANG',
                'code'          => '1205',
                'status'        => 1,
                'dji_product_id' => '400061',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Sleman',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'DI Yogyakarta',
                'region'        => 'KAB SLEMAN',
                'code'          => '1206',
                'status'        => 1,
                'dji_product_id' => '400071',
                'type'          => 'Postpaid',
            ],
            [ 
                'name'          => 'PDAM Kab Boyolali',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB BOYOLALI',
                'code'          => '1207',
                'status'        => 1,
                'dji_product_id' => '400081',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Jepara',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB JEPARA',
                'code'          => '1208',
                'status'        => 1,
                'dji_product_id' => '400091',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Pekalongan',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB PEKALONGAN',
                'code'          => '1209',
                'status'        => 1,
                'dji_product_id' => '400101',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Banjar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Barat',
                'region'        => 'KOTA BANJAR',
                'code'          => '1210',
                'status'        => 1,
                'dji_product_id' => '400111',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Karanganyar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB KARANGANYAR',
                'code'          => '1211',
                'status'        => 1,
                'dji_product_id' => '400121',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Wonogiri',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB WONOGIRI',
                'code'          => '1212',
                'status'        => 1,
                'dji_product_id' => '400141',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Magelang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB MAGELANG',
                'code'          => '1213',
                'status'        => 1,
                'dji_product_id' => '400151',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Situbondo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB SITUBONDO',
                'code'          => '1214',
                'status'        => 1,
                'dji_product_id' => '400161',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Probolinggo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB PROBOLINGGO',
                'code'          => '1215',
                'status'        => 1,
                'dji_product_id' => '400171',
                'type'           => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Sragen',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB SRAGEN',
                'code'          => '1216',
                'status'        => 1,
                'dji_product_id' => '400181',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Bondowoso',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB BONDOWOSO',
                'code'          => '1217',
                'status'        => 1,
                'dji_product_id' => '400191',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Semarang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB SEMARANG',
                'code'          => '1218',
                'status'        => 1,
                'dji_product_id' => '400201',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Purworejo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB PURWOREJO',
                'code'          => '1219',
                'status'        => 1,
                'dji_product_id' => '400211',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Bandung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Barat',
                'region'        => 'KAB BANDUNG',
                'code'          => '1220',
                'status'        => 1,
                'dji_product_id' => '400221',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Banjarmasin',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Kalimantan',
                'region'        => 'KOTA BANJARMASIN',
                'code'          => '1221',
                'status'        => 1,
                'dji_product_id' => '400231',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Kendal',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB KENDAL',
                'code'          => '1222',
                'status'        => 1,
                'dji_product_id' => '400241',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Surakarta',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KOTA SURAKARTA',
                'code'          => '1223',
                'status'        => 1,
                'dji_product_id' => '400251',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Madiun',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KOTA MADIUN',
                'code'          => '1224',
                'status'        => 1,
                'dji_product_id' => '400261',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Purbalingga',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB PURBALINGGA',
                'code'          => '1225',
                'status'        => 1,
                'dji_product_id' => '400271',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Malang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB MALANG',
                'code'          => '1226',
                'status'        => 1,
                'dji_product_id' => '400281',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Rembang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB REMBANG',
                'code'          => '1227',
                'status'        => 1,
                'dji_product_id' => '400301',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Lombok Tengah',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'NTB',
                'region'        => 'KAB LOMBOK TENGAH',
                'code'          => '1228',
                'status'        => 1,
                'dji_product_id' => '400311',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Salatiga',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KOTA SALATIGA',
                'code'          => '1229',
                'status'        => 1,
                'dji_product_id' => '400321',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Wonosobo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB WONOSOBO',
                'code'          => '1230',
                'status'        => 1,
                'dji_product_id' => '400331',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Brebes',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB BREBES',
                'code'          => '1231',
                'status'        => 1,
                'dji_product_id' => '400341',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Jember',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB JEMBER',
                'code'          => '1232',
                'status'        => 1,
                'dji_product_id' => '400351',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Buleleng',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Bali',
                'region'        => 'KAB BULELENG',
                'code'          => '1233',
                'status'        => 1,
                'dji_product_id' => '400371',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Giri Menang Mataram',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'NTB',
                'region'        => 'GIRI MENANG MATARAM',
                'code'          => '1234',
                'status'        => 1,
                'dji_product_id' => '400381',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Intan Banjar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Kalimantan',
                'region'        => 'INTAN BANJAR',
                'code'          => '1235',
                'status'        => 1,
                'dji_product_id' => '400401',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Temanggung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB TEMANGGUNG',
                'code'          => '1236',
                'status'        => 1,
                'dji_product_id' => '400411',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Blora',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB BLORA',
                'code'          => '1237',
                'status'        => 1,
                'dji_product_id' => '400421',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Kudus',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB KUDUS',
                'code'          => '1238',
                'status'        => 1,
                'dji_product_id' => '400431',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Palyja',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'DKI Jakarta',
                'region'        => 'PALYJA',
                'code'          => '1239',
                'status'        => 1,
                'dji_product_id' => '400441',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Aetra',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'DKI Jakarta',
                'region'        => 'AETRA',
                'code'          => '1240',
                'status'        => 1,
                'dji_product_id' => '400451',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Bandung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Barat',
                'region'        => 'KOTA BANDUNG',
                'code'          => '1241',
                'status'        => 1,
                'dji_product_id' => '400461',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Palembang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Sumatera',
                'region'        => 'KOTA PALEMBANG',
                'code'          => '1242',
                'status'        => 1,
                'dji_product_id' => '400481',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Lampung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Sumatera',
                'region'        => 'KOTA LAMPUNG',
                'code'          => '1243',
                'status'        => 1,
                'dji_product_id' => '400501',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Sukoharjo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB SUKOHARJO',
                'code'          => '1244',
                'status'        => 1,
                'dji_product_id' => '400511',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Grobogan',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB GROBOGAN',
                'code'          => '1245',
                'status'        => 1,
                'dji_product_id' => '400521',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kota Denpasar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Bali',
                'region'        => 'KOTA DENPASAR',
                'code'          => '1246',
                'status'        => 1,
                'dji_product_id' => '400541',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Pati',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Tengah',
                'region'        => 'KAB PATI',
                'code'          => '1247',
                'status'        => 1,
                'dji_product_id' => '400591',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Klungkung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Bali',
                'region'        => 'KAB KLUNGKUNG',
                'code'          => '1248',
                'status'        => 1,
                'dji_product_id' => '400601',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Banyuwangi',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB BANYUWANGI',
                'code'          => '1249',
                'status'        => 1,
                'dji_product_id' => '400611',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Ciamis',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Barat',
                'region'        => 'KAB CIAMIS',
                'code'          => '1250',
                'status'        => 1,
                'dji_product_id' => '400621',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Sumedang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Barat',
                'region'        => 'KAB SUMEDANG',
                'code'          => '1251',
                'status'        => 1,
                'dji_product_id' => '400631',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Jombang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB JOMBANG',
                'code'          => '1252',
                'status'        => 1,
                'dji_product_id' => '400651',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Garut',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Barat',
                'region'        => 'KAB GARUT',
                'code'          => '1253',
                'status'        => 1,
                'dji_product_id' => '400661',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'PDAM Kab Ponorogo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'province'      => 'Jawa Timur',
                'region'        => 'KAB PONOROGO',
                'code'          => '1254',
                'status'        => 1,
                'dji_product_id' => '400681',
                'type'          => 'Postpaid',
            ],

            // TV Kabel
            [
                'name'          => 'TransVision',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1301',
                'status'        => 1,
                'dji_product_id' => '520051',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Indovision',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1302',
                'status'        => 1,
                'dji_product_id' => '520031',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Topas TV',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1303',
                'status'        => 1,
                'dji_product_id' => '540021',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Big TV',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1304',
                'status'        => 1,
                'dji_product_id' => '520081',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Nex Media',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1305',
                'status'        => 1,
                'dji_product_id' => '540011',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'K-Vision',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1306',
                'status'        => 1,
                'dji_product_id' => '560011',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Orange TV Postpaid',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1307',
                'status'        => 1,
                'dji_product_id' => '560051',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'TV Kabel',
                'price'         => 50000,
                'province'      => null,
                'region'        => null,
                'code'          => '1308',
                'status'        => 1,
                'dji_product_id' => '770501',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'TV Kabel',
                'price'         => 100000,
                'province'      => null,
                'region'        => null,
                'code'          => '1309',
                'status'        => 1,
                'dji_product_id' => '771001',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 200.000',
                'category'      => 'TV Kabel',
                'price'         => 200000,
                'province'      => null,
                'region'        => null,
                'code'          => '1310',
                'status'        => 1,
                'dji_product_id' => '772001',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 300.000',
                'category'      => 'TV Kabel',
                'price'         => 300000,
                'province'      => null,
                'region'        => null,
                'code'          => '1311',
                'status'        => 1,
                'dji_product_id' => '770501',
                'type'          => 'Prepaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 1 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1312',
                'status'        => 1,
                'dji_product_id' => '560121',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 3 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1313',
                'status'        => 1,
                'dji_product_id' => '560221',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 6 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1314',
                'status'        => 1,
                'dji_product_id' => '560321',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 12 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1315',
                'status'        => 1,
                'dji_product_id' => '560421',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 1 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1316',
                'status'        => 1,
                'dji_product_id' => '560521',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 3 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1317',
                'status'        => 1,
                'dji_product_id' => '560621',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 6 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1318',
                'status'        => 1,
                'dji_product_id' => '560721',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 12 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1319',
                'status'        => 1,
                'dji_product_id' => '560821',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Mandarin 1 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1320',
                'status'        => 1,
                'dji_product_id' => '560921',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Mandarin 3 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1321',
                'status'        => 1,
                'dji_product_id' => '561021',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Mandarin 6 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1322',
                'status'        => 1,
                'dji_product_id' => '561121',
                'type'          => 'Postpaid',
            ],

            // Pulsa Pascabayar
            [
                'name'          => 'Halo',
                'variant_name'  => null,
                'category'      => 'Pulsa',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1401',
                'status'        => 1,
                'dji_product_id' => '520021',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Smart',
                'variant_name'  => null,
                'category'      => 'Pulsa',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1402',
                'status'        => 1,
                'dji_product_id' => '560031',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Xplor',
                'variant_name'  => null,
                'category'      => 'Pulsa',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1403',
                'status'        => 1,
                'dji_product_id' => '550041',
                'type'          => 'Postpaid',
            ],

            // Telepon (Telkom)
            [
                'name'          => 'Telkom Group',
                'variant_name'  => null,
                'category'      => 'Telepon',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1501',
                'status'        => 1,
                'dji_product_id' => '520011',
                'type'          => 'Postpaid',
            ],

            // Angsuran Kredit
            [
                'name'          => 'FIF',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1601',
                'status'        => 1,
                'dji_product_id' => '204111',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'WOM',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1602',
                'status'        => 1,
                'dji_product_id' => '212111',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Columbia',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1603',
                'status'        => 1,
                'dji_product_id' => '206121',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'Mega Finance',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1604',
                'status'        => 1,
                'dji_product_id' => '201111',
                'type'          => 'Postpaid',
            ],
            [
                'name'          => 'BAF',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1605',
                'status'        => 1,
                'dji_product_id' => '212121',
                'type'          => 'Postpaid',
            ],

            // BPJS
            [
                'name'          => 'BPJS Kesehatan',
                'variant_name'  => null,
                'category'      => 'BPJS',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1701',
                'status'        => 1,
                'dji_product_id' => '900001',
                'type'          => 'Postpaid',
            ],
            
            // Streaming
            [
                'name'          => 'Genflix',
                'variant_name'  => null,
                'category'      => 'Streaming',
                'price'         => null,
                'province'      => null,
                'region'        => null,
                'code'          => '1801',
                'status'        => 1,
                'dji_product_id' => '570021',
                'type'          => 'Postpaid',
            ],
            
        ]);
    }
}
