<?php

use Illuminate\Database\Seeder;

use Faker\Factory;
use App\Product;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	Product::insert([
            // Saldo
            [
                'name'          => 'Donkpet',
                'variant_name'  => null,
                'category'      => 'Saldo',
                'price'         => null,
                'code'          => '1001',
                'dji_product_id' => null,
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // Tagihan Listrik
            [
                'name'          => 'Tagihan Listrik',
                'variant_name'  => null,
                'category'      => 'PLN',
                'price'         => null,
                'code'          => '1101',
                'dji_product_id' => '100301',
                'type'          => 'Postpaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // Token Listrik
    		[
	            'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 20.000',
                'category'      => 'PLN',
                'price'         => 20000,
	            'code'          => '1111',
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'PLN',
                'price'         => 50000,
                'code'          => '1112',
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'PLN',
                'price'         => 100000,
                'code'          => '1113',
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 200.000',
                'category'      => 'PLN',
                'price'         => 200000,
                'code'          => '1114',
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 500.000',
                'category'      => 'PLN',
                'price'         => 500000,
                'code'          => '1115',
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Token Listrik',
                'variant_name'  => 'Rp 1.000.000',
                'category'      => 'PLN',
                'price'         => 1000000,
                'code'          => '1107',
                'dji_product_id' => '100302',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // PDAM
            [
                'name'          => 'PDAM Kab Banyumas',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1201',
                'dji_product_id' => '400011',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Kebumen',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1202',
                'dji_product_id' => '400021',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Magelang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1203',
                'dji_product_id' => '400041',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Cilacap',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1204',
                'dji_product_id' => '400051',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Semarang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1205',
                'dji_product_id' => '400061',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Sleman',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1206',
                'dji_product_id' => '400071',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [ 
                'name'          => 'PDAM Kab Boyolali',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1207',
                'dji_product_id' => '400081',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Jepara',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1208',
                'dji_product_id' => '400091',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Pekalongan',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1209',
                'dji_product_id' => '400101',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Banjar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1210',
                'dji_product_id' => '400111',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Karanganyar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1211',
                'dji_product_id' => '400121',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Wonogiri',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1212',
                'dji_product_id' => '400141',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Magelang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1213',
                'dji_product_id' => '400151',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Situbondo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1214',
                'dji_product_id' => '400161',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Probolinggo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1215',
                'dji_product_id' => '400171',
                'type'           => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Sragen',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1216',
                'dji_product_id' => '400181',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Bondowoso',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1217',
                'dji_product_id' => '400191',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Semarang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1218',
                'dji_product_id' => '400201',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Purworejo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1219',
                'dji_product_id' => '400211',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Bandung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1220',
                'dji_product_id' => '400221',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Banjarmasin',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1221',
                'dji_product_id' => '400231',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Kendal',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1222',
                'dji_product_id' => '400241',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Surakarta',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1223',
                'dji_product_id' => '400251',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Madiun',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1224',
                'dji_product_id' => '400261',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Purbalingga',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1225',
                'dji_product_id' => '400271',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Malang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1226',
                'dji_product_id' => '400281',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Rembang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1227',
                'dji_product_id' => '400301',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Lombok Tengah',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1228',
                'dji_product_id' => '400311',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Salatiga',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1229',
                'dji_product_id' => '400321',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Wonosobo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1230',
                'dji_product_id' => '400331',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Brebes',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1231',
                'dji_product_id' => '400341',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Jember',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1232',
                'dji_product_id' => '400351',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Buleleng',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1233',
                'dji_product_id' => '400371',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Giri Menang Mataram',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1234',
                'dji_product_id' => '400381',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Intan Banjar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1235',
                'dji_product_id' => '400401',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Temanggung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1236',
                'dji_product_id' => '400411',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Blora',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1237',
                'dji_product_id' => '400421',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Kudus',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1238',
                'dji_product_id' => '400431',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Palyja',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1239',
                'dji_product_id' => '400441',
                'type'          => 'Postpaid',
                'image_name'    => 'palyja.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Aetra',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1240',
                'dji_product_id' => '400451',
                'type'          => 'Postpaid',
                'image_name'    => 'aetra.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Bandung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1241',
                'dji_product_id' => '400461',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Palembang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1242',
                'dji_product_id' => '400481',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Lampung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1243',
                'dji_product_id' => '400501',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Sukoharjo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1244',
                'dji_product_id' => '400511',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Grobogan',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1245',
                'dji_product_id' => '400521',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kota Denpasar',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1246',
                'dji_product_id' => '400541',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Pati',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1247',
                'dji_product_id' => '400591',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Klungkung',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1248',
                'dji_product_id' => '400601',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Banyuwangi',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1249',
                'dji_product_id' => '400611',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Ciamis',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1250',
                'dji_product_id' => '400621',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Sumedang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1251',
                'dji_product_id' => '400631',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Jombang',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1252',
                'dji_product_id' => '400651',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Garut',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1253',
                'dji_product_id' => '400661',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],
            [
                'name'          => 'PDAM Kab Ponorogo',
                'variant_name'  => null,
                'category'      => 'PDAM',
                'price'         => null,
                'code'          => '1254',
                'dji_product_id' => '400681',
                'type'          => 'Postpaid',
                'image_name'    => 'pam.png',
                'status'        => 1,
            ],

            // TV Kabel
            [
                'name'          => 'TransVision',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1301',
                'dji_product_id' => '520051',
                'type'          => 'Postpaid',
                'image_name'    => 'transvision.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indovision',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1302',
                'dji_product_id' => '520031',
                'type'          => 'Postpaid',
                'image_name'    => 'indovision.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Topas TV',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1303',
                'dji_product_id' => '540021',
                'type'          => 'Postpaid',
                'image_name'    => 'topas_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Big TV',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1304',
                'dji_product_id' => '520081',
                'type'          => 'Postpaid',
                'image_name'    => 'big_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Nex Media',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1305',
                'dji_product_id' => '540011',
                'type'          => 'Postpaid',
                'image_name'    => 'nexmedia.png',
                'status'        => 1,
            ],
            [
                'name'          => 'K-Vision',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1306',
                'dji_product_id' => '560011',
                'type'          => 'Prepaid',
                'image_name'    => 'k_vision.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Orange TV Postpaid',
                'variant_name'  => null,
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1307',
                'dji_product_id' => '560051',
                'type'          => 'Postpaid',
                'image_name'    => 'orange_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'TV Kabel',
                'price'         => 50000,
                'code'          => '1308',
                'dji_product_id' => '770501',
                'type'          => 'Prepaid',
                'image_name'    => 'orange_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'TV Kabel',
                'price'         => 100000,
                'code'          => '1309',
                'dji_product_id' => '771001',
                'type'          => 'Prepaid',
                'image_name'    => 'orange_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 200.000',
                'category'      => 'TV Kabel',
                'price'         => 200000,
                'code'          => '1310',
                'dji_product_id' => '772001',
                'type'          => 'Prepaid',
                'image_name'    => 'orange_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Orange TV Prepaid',
                'variant_name'  => 'Rp 300.000',
                'category'      => 'TV Kabel',
                'price'         => 300000,
                'code'          => '1311',
                'dji_product_id' => '770501',
                'type'          => 'Prepaid',
                'image_name'    => 'orange_tv.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 1 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1312',
                'dji_product_id' => '560121',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 3 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1313',
                'dji_product_id' => '560221',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 6 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1314',
                'dji_product_id' => '560321',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Family 12 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1315',
                'dji_product_id' => '560421',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 1 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1316',
                'dji_product_id' => '560521',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 3 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1317',
                'dji_product_id' => '560621',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 6 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1318',
                'dji_product_id' => '560721',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Deluxe 12 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1319',
                'dji_product_id' => '560821',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Mandarin 1 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1320',
                'dji_product_id' => '560921',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Mandarin 3 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1321',
                'dji_product_id' => '561021',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Skynindo',
                'variant_name'  => 'Mandarin 6 Bulan',
                'category'      => 'TV Kabel',
                'price'         => null,
                'code'          => '1322',
                'dji_product_id' => '561121',
                'type'          => 'Prepaid',
                'image_name'    => 'skynindo.png',
                'status'        => 1,
            ],

            // Pulsa Pascabayar
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Halo',
                'category'      => 'Pulsa',
                'price'         => null,
                'code'          => '1401',
                'dji_product_id' => '520021',
                'type'          => 'Postpaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Smartfren',
                'variant_name'  => null,
                'category'      => 'Pulsa',
                'price'         => null,
                'code'          => '1402',
                'dji_product_id' => '560031',
                'type'          => 'Postpaid',
                'image_name'    => 'smartfren.png',
                'status'        => 1,
            ],
            [
                'name'          => 'XL',
                'variant_name'  => null,
                'category'      => 'Pulsa',
                'price'         => null,
                'code'          => '1403',
                'dji_product_id' => '550041',
                'type'          => 'Postpaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],

            // Pulsa Prabayar
            // Indosat
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Rp 5.000',
                'category'      => 'Pulsa',
                'price'         => 5000,
                'code'          => '1411',
                'dji_product_id' => '500511',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Rp 10.000',
                'category'      => 'Pulsa',
                'price'         => 10000,
                'code'          => '1412',
                'dji_product_id' => '501011',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1413',
                'dji_product_id' => '502511',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1414',
                'dji_product_id' => '505011',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1415',
                'dji_product_id' => '510011',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],

            // Telkomsel
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Rp 5.000',
                'category'      => 'Pulsa',
                'price'         => 5000,
                'code'          => '1421',
                'dji_product_id' => '500521',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Rp 10.000',
                'category'      => 'Pulsa',
                'price'         => 10000,
                'code'          => '1422',
                'dji_product_id' => '501021',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1423',
                'dji_product_id' => '502521',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1424',
                'dji_product_id' => '505021',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1425',
                'dji_product_id' => '510021',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],

            // XL
            [
                'name'          => 'XL',
                'variant_name'  => 'Rp 5.000',
                'category'      => 'Pulsa',
                'price'         => 5000,
                'code'          => '1431',
                'dji_product_id' => '500531',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],
            [
                'name'          => 'XL',
                'variant_name'  => 'Rp 10.000',
                'category'      => 'Pulsa',
                'price'         => 10000,
                'code'          => '1432',
                'dji_product_id' => '501031',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],
            [
                'name'          => 'XL',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1433',
                'dji_product_id' => '502531',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],
            [
                'name'          => 'XL',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1434',
                'dji_product_id' => '505031',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],
            [
                'name'          => 'XL',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1435',
                'dji_product_id' => '510031',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],

            // 3
            [
                'name'          => '3',
                'variant_name'  => 'Rp 5.000',
                'category'      => 'Pulsa',
                'price'         => 5000,
                'code'          => '1441',
                'dji_product_id' => '500541',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],
            [
                'name'          => '3',
                'variant_name'  => 'Rp 10.000',
                'category'      => 'Pulsa',
                'price'         => 10000,
                'code'          => '1442',
                'dji_product_id' => '501041',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],
            [
                'name'          => '3',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1443',
                'dji_product_id' => '502541',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],
            [
                'name'          => '3',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1444',
                'dji_product_id' => '505041',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],
            [
                'name'          => '3',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1445',
                'dji_product_id' => '510041',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],

            // Axis
            [
                'name'          => 'Axis',
                'variant_name'  => 'Rp 5.000',
                'category'      => 'Pulsa',
                'price'         => 5000,
                'code'          => '1451',
                'dji_product_id' => '500551',
                'type'          => 'Prepaid',
                'image_name'    => 'axis.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Axis',
                'variant_name'  => 'Rp 10.000',
                'category'      => 'Pulsa',
                'price'         => 10000,
                'code'          => '1452',
                'dji_product_id' => '501051',
                'type'          => 'Prepaid',
                'image_name'    => 'axis.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Axis',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1453',
                'dji_product_id' => '502551',
                'type'          => 'Prepaid',
                'image_name'    => 'axis.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Axis',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1454',
                'dji_product_id' => '505051',
                'type'          => 'Prepaid',
                'image_name'    => 'axis.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Axis',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1455',
                'dji_product_id' => '510051',
                'type'          => 'Prepaid',
                'image_name'    => 'axis.png',
                'status'        => 1,
            ],

            // Smartfren
            [
                'name'          => 'Smartfren',
                'variant_name'  => 'Rp 5.000',
                'category'      => 'Pulsa',
                'price'         => 5000,
                'code'          => '1461',
                'dji_product_id' => '500581',
                'type'          => 'Prepaid',
                'image_name'    => 'smartfren.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Smartfren',
                'variant_name'  => 'Rp 10.000',
                'category'      => 'Pulsa',
                'price'         => 10000,
                'code'          => '1462',
                'dji_product_id' => '501081',
                'type'          => 'Prepaid',
                'image_name'    => 'smartfren.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Smartfren',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1463',
                'dji_product_id' => '502581',
                'type'          => 'Prepaid',
                'image_name'    => 'smartfren.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Smartfren',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1464',
                'dji_product_id' => '505081',
                'type'          => 'Prepaid',
                'image_name'    => 'smartfren.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Smartfren',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1465',
                'dji_product_id' => '510081',
                'type'          => 'Prepaid',
                'image_name'    => 'smartfren.png',
                'status'        => 1,
            ],

            // Bolt
            [
                'name'          => 'Bolt',
                'variant_name'  => 'Rp 25.000',
                'category'      => 'Pulsa',
                'price'         => 25000,
                'code'          => '1471',
                'dji_product_id' => '502591',
                'type'          => 'Prepaid',
                'image_name'    => 'bolt.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Bolt',
                'variant_name'  => 'Rp 50.000',
                'category'      => 'Pulsa',
                'price'         => 50000,
                'code'          => '1472',
                'dji_product_id' => '505091',
                'type'          => 'Prepaid',
                'image_name'    => 'bolt.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Bolt',
                'variant_name'  => 'Rp 100.000',
                'category'      => 'Pulsa',
                'price'         => 100000,
                'code'          => '1473',
                'dji_product_id' => '510091',
                'type'          => 'Prepaid',
                'image_name'    => 'bolt.png',
                'status'        => 1,
            ],

            // Telkom
            [
                'name'          => 'Telkom Group',
                'variant_name'  => null,
                'category'      => 'Telkom',
                'price'         => null,
                'code'          => '1501',
                'dji_product_id' => '520011',
                'type'          => 'Postpaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // Angsuran Kredit
            [
                'name'          => 'FIF Finance',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'code'          => '1601',
                'dji_product_id' => '204111',
                'type'          => 'Postpaid',
                'image_name'    => 'fif.png',
                'status'        => 1,
            ],
            [
                'name'          => 'WOM Finance',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'code'          => '1602',
                'dji_product_id' => '212111',
                'type'          => 'Postpaid',
                'image_name'    => 'wom.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Columbia Finance',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'code'          => '1603',
                'dji_product_id' => '206121',
                'type'          => 'Postpaid',
                'image_name'    => 'columbia.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Mega Finance',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'code'          => '1604',
                'dji_product_id' => '201111',
                'type'          => 'Postpaid',
                'image_name'    => 'mega.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Bussan Auto Finance',
                'variant_name'  => null,
                'category'      => 'Angsuran Kredit',
                'price'         => null,
                'code'          => '1605',
                'dji_product_id' => '212121',
                'type'          => 'Postpaid',
                'image_name'    => 'baf.png',
                'status'        => 1,
            ],

            // BPJS
            [
                'name'          => 'BPJS Kesehatan',
                'variant_name'  => null,
                'category'      => 'BPJS',
                'price'         => null,
                'code'          => '1701',
                'dji_product_id' => '900001',
                'type'          => 'Postpaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            
            // Streaming
            [
                'name'          => 'Genflix',
                'variant_name'  => null,
                'category'      => 'Streaming',
                'price'         => null,
                'code'          => '1801',
                'dji_product_id' => '570021',
                'type'          => 'Postpaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // Paket Data
            // Indosat
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Data 1GB',
                'category'      => 'Paket Data',
                'price'         => 10000,
                'code'          => '1901',
                'dji_product_id' => '5D0111',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Data 2GB',
                'category'      => 'Paket Data',
                'price'         => 20000,
                'code'          => '1902',
                'dji_product_id' => '5D0211',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Data 3GB',
                'category'      => 'Paket Data',
                'price'         => 30000,
                'code'          => '1903',
                'dji_product_id' => '5D0311',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Data 3GB (Regular 1,5GB)',
                'category'      => 'Paket Data',
                'price'         => 40000,
                'code'          => '1904',
                'dji_product_id' => '5D0411',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Data 5GB',
                'category'      => 'Paket Data',
                'price'         => 50000,
                'code'          => '1905',
                'dji_product_id' => '5D0511',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Indosat',
                'variant_name'  => 'Data 6,5GB (Regular 3GB)',
                'category'      => 'Paket Data',
                'price'         => 60000,
                'code'          => '1906',
                'dji_product_id' => '5D0611',
                'type'          => 'Prepaid',
                'image_name'    => 'indosat.png',
                'status'        => 1,
            ],

            // Telkomsel
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Data 80MB',
                'category'      => 'Paket Data',
                'price'         => 25000,
                'code'          => '1911',
                'dji_product_id' => '5D0221',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Data 300MB',
                'category'      => 'Paket Data',
                'price'         => 35000,
                'code'          => '1912',
                'dji_product_id' => '5D0321',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],
            [
                'name'          => 'Telkomsel',
                'variant_name'  => 'Data 400MB',
                'category'      => 'Paket Data',
                'price'         => 45000,
                'code'          => '1913',
                'dji_product_id' => '5D0421',
                'type'          => 'Prepaid',
                'image_name'    => 'telkomsel.png',
                'status'        => 1,
            ],

            // XL
            [
                'name'          => 'XL',
                'variant_name'  => 'HotRod 3GB',
                'category'      => 'Paket Data',
                'price'         => 16000,
                'code'          => '1921',
                'dji_product_id' => '5D0631',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],
            [
                'name'          => 'XL',
                'variant_name'  => 'HotRod 4GB',
                'category'      => 'Paket Data',
                'price'         => 25000,
                'code'          => '1922',
                'dji_product_id' => '5D1131',
                'type'          => 'Prepaid',
                'image_name'    => 'xl.png',
                'status'        => 1,
            ],

            // 3
            [
                'name'          => '3',
                'variant_name'  => 'Data 1GB',
                'category'      => 'Paket Data',
                'price'         => 51000,
                'code'          => '1931',
                'dji_product_id' => '5D0341',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],
            [
                'name'          => '3',
                'variant_name'  => 'Data 2GB',
                'category'      => 'Paket Data',
                'price'         => 52000,
                'code'          => '1932',
                'dji_product_id' => '5D0441',
                'type'          => 'Prepaid',
                'image_name'    => '3.png',
                'status'        => 1,
            ],

            // Voucher Game
            [
                'name'          => 'Aeria Games',
                'variant_name'  => 'GAR-510',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2001',
                'dji_product_id' => '6061AA',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Aeria Games',
                'variant_name'  => 'GAR-2120',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2002',
                'dji_product_id' => '6246AA',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Aeria Games',
                'variant_name'  => 'GAR-1040',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2003',
                'dji_product_id' => '6123AA',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Aeria Games',
                'variant_name'  => 'GAR-3240',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2004',
                'dji_product_id' => '6369AA',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Aeria Games',
                'variant_name'  => 'GAR-5500',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2005',
                'dji_product_id' => '6615AA',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Aeria Games',
                'variant_name'  => 'GAR-8550',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2006',
                'dji_product_id' => '6922AA',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // Asiasoft SEA
            [
                'name'          => 'Asiasoft SEA',
                'variant_name'  => 'GAC-V5000',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2011',
                'dji_product_id' => '6049AB',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Asiasoft SEA',
                'variant_name'  => 'GAC-V10000',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2012',
                'dji_product_id' => '6098AB',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Asiasoft SEA',
                'variant_name'  => 'GAC-V30000',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2013',
                'dji_product_id' => '6294AB',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            
            // Cherry Credits
            [
                'name'          => 'Cherry Credits',
                'variant_name'  => 'VCC-V50',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2021',
                'dji_product_id' => '6049AC',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Cherry Credits',
                'variant_name'  => 'VCC-V100',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2022',
                'dji_product_id' => '6098AC',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Cherry Credits',
                'variant_name'  => 'VCC-V300',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2023',
                'dji_product_id' => '6294AC',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // E Games Hub
            [
                'name'          => 'E Games Hub',
                'variant_name'  => 'GEP-500P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2031',
                'dji_product_id' => '6020AD',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'E Games Hub',
                'variant_name'  => 'GEP-2000P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2032',
                'dji_product_id' => '6080AD',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'E Games Hub',
                'variant_name'  => 'GEP-5000P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2033',
                'dji_product_id' => '6200AD',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            
            // Funnel Asia
            [
                'name'          => 'Funnel Asia',
                'variant_name'  => 'GFP-V300',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2041',
                'dji_product_id' => '6040AF',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Funnel Asia',
                'variant_name'  => 'GFP-V1000',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2042',
                'dji_product_id' => '6128AF',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Funnel Asia',
                'variant_name'  => 'GFP-V2000',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2043',
                'dji_product_id' => '6256AF',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Funnel Asia',
                'variant_name'  => 'GFP-V5000',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2044',
                'dji_product_id' => '6640AF',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],

            // Gameview
            [
                'name'          => 'Gameview',
                'variant_name'  => 'GGV-100P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2051',
                'dji_product_id' => '6040AG',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Gameview',
                'variant_name'  => 'GGV-300P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2052',
                'dji_product_id' => '6120AG',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Gameview',
                'variant_name'  => 'GGV-500P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2053',
                'dji_product_id' => '6200AG',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Gameview',
                'variant_name'  => 'GGV-1000P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2054',
                'dji_product_id' => '6400AG',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
            [
                'name'          => 'Gameview',
                'variant_name'  => 'GGV-2000P',
                'category'      => 'Voucher Game',
                'price'         => null,
                'code'          => '2055',
                'dji_product_id' => '6800AG',
                'type'          => 'Prepaid',
                'image_name'    => null,
                'status'        => 1,
            ],
        ]);
    }
}
