before_script:
    - pwd
    - git status

stages:
    - test
    - deploy

test:
    stage: test
    script:
        - /usr/local/bin/composer install

deploy:
    stage: deploy
    only:
        - dev
    script:
        - git push dev HEAD:dev
