before_script:
    - pwd
    - git status

stages:
    - test
    - deploy

deploy:
    stage: deploy
    only:
        - dev
    script:
        - git remote -v
        - git remote add staging root@104.236.115.202:/var/www/PayDonk.git 
        - git push staging dev
