before_script:
  - '[[ ! -e /.dockerenv ]] && exit 0'

deploy_staging:
    stage: deploy
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - ssh root@104.236.115.202 "cd ~/var/www/PayDonk && git pull origin dev && ~/bin/composer install"
    only:
        - dev
