before_script:
    - bundle install

after_script:
    - rm secrets

stages:
    - build
    - test
    - deploy

job1:
    stage: build
    script:
        - execute-script-for-job1
    only:
        - master
    tags:
        - docker
